### ISSUE TITLE
Metadata-version 1.1 or 2.0?

### ISSUE THREAD

**Issue by Zearin** [ccpgames/pypackage#14]
I just noticed that if I run `py-info, the output begins with:

    Metadata-Version: 2.0

But when I run `py-build` on my own project, the `PKG-INFO` begins with:

    Metadata-Version: 1.1

I don’t know much about Python’s metadata standards, though.  (I _think_ I recall reading something about updating the PyPI metadata format, but I dunno if it’s related.)

**Comment by a-tal** [comment]
current version is 1.1, there's an accepted PEP for 1.2 though (PEP-345).

I'm setting ahead of 1.2 though, because of implementing PEP-426 early. Thanks for bringing this up though, found an inconstancy where v 1.0 was being output.

If you see that it's down to metadata-version: 1.1 the `PKG-INFO` file was remade at some point.
